global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: api-gateway
    metrics_path: /metrics
    static_configs:
      - targets: ["api-gateway:8000"]

  - job_name: product-service
    metrics_path: /metrics
    static_configs:
      - targets: ["product-service:8001"]

  - job_name: order-service
    metrics_path: /metrics
    static_configs:
      - targets: ["order-service:8002"]
